$(function(){
	$("#jigoujianjie").click(function(){
		$("#all_application_of_testing").css("display","none");
	});
	$("#wenhualiliang").click(function(){
		$("#all_application_of_testing").css("display","none");
	});
	$("#chengpinyingcai").click(function(){
		$("#all_application_of_testing").css("display","none");
	});
	$("#zuixingonggao").click(function(){
		$("#all_application_of_testing").css("display","block");
	});
});